import Head from "next/head";
import Image from "next/image";
import Link from "next/Link";
import toast from "react-hot-toast";
import axios from "axios";
import SignInForm from "../../components/forms/sign-in";
import SignUpForm from "../../components/forms/sign-up";
import { useRouter } from "next/router";
import { useState } from "react";
import { setCookie, hasCookie } from "cookies-next";
import styles from "../../styles/styles.module.scss";

export const getServerSideProps = ({ req, res }) => {
  const isAuthenticated = hasCookie("jwt", { req, res });
  if (isAuthenticated) {
    return {
      redirect: {
        permanent: false,
        destination: "/",
      },
    };
  }
  return { props: {} };
};

export default function Home() {
  const [toggleForm, setToggleForm] = useState(false);
  const router = useRouter();

  const createAccount = async (formData) => {
    try {
      await axios.post(`${process.env.NEXT_PUBLIC_API_URL}/user`, formData);
      setToggleForm(true);
      toast.success("Account created successfully!");
    } catch (err) {
      if (err?.response?.data?.message.includes("duplicate")) {
        return toast.error("This email has already been taken!");
      }
      toast.error(`${err?.response?.data?.message}`);
    }
  };

  const signIn = async (formData) => {
    try {
      const { data } = await axios.post(
        `${process.env.NEXT_PUBLIC_API_URL}/auth`,
        formData
      );
      setCookie("jwt", data);
      router.push("/");
      toast.success("You are logged!");
    } catch (err) {
      toast.error(`${err?.response?.data?.message}`);
    }
  };

  return (
    <>
      <Head>
        <title>Better-U | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container">
          <div className="row">
            <div className="col-4">
              <h1 className={styles.title}>Better-U</h1>
              <p className={styles.paragraph}>
                Where self-improvement meets social connection
              </p>
            </div>
            <div className="col-8 d-flex justify-content-center">
              <div>
                {toggleForm ? (
                  <>
                    <SignInForm signIn={signIn} />
                    <Link
                      href=""
                      onClick={() => {
                        setToggleForm(
                          (toggleForm) => (toggleForm = !toggleForm)
                        );
                      }}
                    >
                      Create account
                    </Link>
                  </>
                ) : (
                  <>
                    <SignUpForm createAccount={createAccount} />
                    <span className="d-block">
                      Have an account?{" "}
                      <Link
                        href=""
                        onClick={() => {
                          setToggleForm(
                            (toggleForm) => (toggleForm = !toggleForm)
                          );
                        }}
                      >
                        Sign-in
                      </Link>
                    </span>
                  </>
                )}
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
