import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import Link from "next/Link";
import toast from "react-hot-toast";
import PostForm from "../components/forms/post";
import NavBar from "../components/nav-bar";
import useSWR from "swr";
import { useRouter } from "next/router";
import { getCookie, deleteCookie } from "cookies-next";

export const getServerSideProps = ({ req, res }) => {
  const data = getCookie("jwt", { req, res });
  if (!data) {
    return {
      redirect: {
        permanent: false,
        destination: "/login",
      },
    };
  }
  return { props: { data: data } };
};

export default function BetterUPage(props) {
  const apiUrl = process.env.NEXT_PUBLIC_API_URL;
  const fetcher = async (url) =>
    await axios.get(url, {
      headers: {
        Authorization: `Bearer ${props.data}`,
      },
    });

  const users = useSWR(`${apiUrl}/user`, fetcher);
  const currentUser = useSWR(`${apiUrl}/user/me`, fetcher);
  const posts = useSWR(`${apiUrl}/posts`, fetcher);

  return (
    <>
      <Head>
        <title>Better-U</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar />
        <div className="container">
          <div className="row">
            {/* componente do perfil na esquerda */}
            <div className="col-3">
              Current user
              <h1>{currentUser.data?.data.username}</h1>
            </div>

            {/* componente central com barra de postagem e posts */}
            <div className="col-6">
              Posts
              <h3>{currentUser.data?.data.username}</h3>
              <PostForm data={props.data} posts={posts} />
              <ul>
                {posts?.data?.data?.posts?.map((post, i) => {
                  return (
                    <li key={i}>
                      <span>{post.user.username}</span>
                      <br></br>
                      <span>{post.text}</span>
                    </li>
                  );
                })}
              </ul>
            </div>

            {/* componente com lista de amigos na direita */}
            <div className="col-3">
              Users
              <ul>
                {users?.data?.data?.map((user, i) => {
                  return <li key={i}>{user.name}</li>;
                })}
              </ul>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
